# -*- coding: utf-8 -*-
"""تنظيم فايل الكود النهائي .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QFKgYRdp99_kJbNhxFRKUQr5Lw5Is-MK
"""



import pandas as pd
import numpy as np
from google.colab import drive

# 1. ربط Google Colab بحساب الدرايف الخاص بكِ
drive.mount('/content/drive')



import pandas as pd

# 1. تحديد مسار الملف
FILE_PATH = '/content/drive/MyDrive/Final_Merged_Corrected.xlsx'

# قراءة البيانات
try:
    df = pd.read_excel(FILE_PATH, sheet_name=0)
except:
    df = pd.read_csv(FILE_PATH)

# ==========================================
# أولاً: رؤية القطاعات كما هي (نفس صورتك بالضبط)
# ==========================================
print("🔴 === القطاعات قبل التوحيد (الوضع الحالي) ===")
counts_before = df['القطاعات'].value_counts()
print(counts_before.head(20)) # طباعة أعلى 20 قطاع
print(f"\n>> إجمالي عدد القطاعات الفريدة (المبعثرة): {df['القطاعات'].nunique()} قطاع\n")
print("-" * 50)

# ==========================================
# ثانياً: تطبيق سحر توحيد الترتيب الأبجدي
# ==========================================
def unify_sectors(sector_string):
    if pd.isna(sector_string):
        return sector_string
    # تقسيم النص بناءً على الفاصل (|) وتنظيف المسافات
    parts = [part.strip() for part in str(sector_string).split('|')]
    # ترتيب القطاعات أبجدياً
    parts.sort()
    # إعادة دمجها
    return ' | '.join(parts)

# إنشاء عمود جديد لنرى الفرق دون مسح القديم
df['القطاعات_الموحدة'] = df['القطاعات'].apply(unify_sectors)

# ==========================================
# ثالثاً: رؤية القطاعات بعد التوحيد
# ==========================================
print("🟢 === القطاعات بعد التوحيد الأبجدي ===")
counts_after = df['القطاعات_الموحدة'].value_counts()
print(counts_after.head(20)) # طباعة أعلى 20 قطاع
print(f"\n>> إجمالي عدد القطاعات الفريدة (النظيفة): {df['القطاعات_الموحدة'].nunique()} قطاع")



# كود استكشاف الجمل الدلالية المستهدفة
print("🎯 تحليل الجمل الدلالية (Target Sentences):")
target_counts = df['enhanced_semantic_sentence'].value_counts()

print(f"✅ إجمالي عدد الجمل الدلالية الفريدة: {len(target_counts)}")
print("-" * 50)
print("📈 أعلى 10 جمل دلالية تكراراً في البيانات:")
print(target_counts.head(10))

# رؤية عينة عشوائية للربط بين النص الخام والهدف الدلالي
print("\n🔍 عينة من خريطة الربط (Raw Text -> Semantic Target):")
sample_mapping = df[['text', 'enhanced_semantic_sentence']].sample(10)
for i, row in sample_mapping.iterrows():
    print(f"📝 النص الخام: {row['text'][:100]}...")
    print(f"➡️  الهدف الدلالي: {row['enhanced_semantic_sentence']}")
    print("-" * 30)



import pandas as pd
import re

FILE_PATH = '/content/drive/MyDrive/Final_Merged_Corrected.xlsx'
SAVE_PATH = '/content/drive/MyDrive/Perfect_Data.xlsx'

# 1. قراءة البيانات
try:
    df = pd.read_excel(FILE_PATH, sheet_name=0)
except:
    df = pd.read_csv(FILE_PATH)

df = df.dropna(subset=['text', 'enhanced_semantic_sentence'])
print(f"📊 عدد السجلات الأصلي: {len(df)}")

# ==========================================
# أ. توحيد القطاعات الأبجدي (الحل السحري)
# ==========================================
def unify_sectors(sector_string):
    if pd.isna(sector_string): return ""
    parts = [part.strip() for part in str(sector_string).split('|')]
    parts.sort()
    return ' '.join(parts) # دمج بدون علامة |

df['القطاعات'] = df['القطاعات'].apply(unify_sectors)

# ==========================================
# ب. توحيد الحروف العربية (Arabic Normalization)
# ==========================================
def normalize_arabic(text):
    if pd.isna(text): return ""
    text = str(text)
    text = re.sub("[إأآا]", "ا", text)
    text = re.sub("ى", "ي", text)
    text = re.sub("ة", "ه", text)
    return text.strip()

df['enhanced_semantic_sentence'] = df['enhanced_semantic_sentence'].apply(normalize_arabic)

# ==========================================
# ج. قص الديباجات الملكية والدستورية من النص الخام
# ==========================================
def clean_raw_text(text):
    if pd.isna(text): return ""
    text = str(text)
    text = normalize_arabic(text) # توحيد الحروف أولاً

    # إزالة الديباجات التي تشتت الموديل
    text = re.sub(r'نحن.*?ملك المملكه الاردنيه الهاشميه', '', text)
    text = re.sub(r'نحن.*?نائب جلاله الملك المعظم', '', text)
    text = re.sub(r'بمقتضي الماده.*?من الدستور', '', text)
    text = re.sub(r'وبناء علي ما قرره مجلس الوزراء.*?نامر بما هو ات', '', text)

    # تنظيف المسافات
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

df['text'] = df['text'].apply(clean_raw_text)

# ==========================================
# د. فلتر الطول وإزالة التكرار (الأمان الأخير)
# ==========================================
# نرفض فقط الجمل الدلالية القصيرة جداً (أقل من 3 كلمات) لأنها لا تحمل دلالة
def is_valid_length(text):
    return len(str(text).split()) >= 3

length_mask = df['enhanced_semantic_sentence'].apply(is_valid_length)
df = df[length_mask]

# إزالة التكرار المتطابق
df = df.drop_duplicates(subset=['القطاعات', 'text', 'enhanced_semantic_sentence'])

# ==========================================
# حفظ النسخة الذهبية
# ==========================================
print(f"\n✨ عدد السجلات النهائي والمثالي: {len(df)}")
print(f"🏷️ عدد القطاعات الفريدة (النظيف): {df['القطاعات'].nunique()}")

df.to_excel(SAVE_PATH, index=False)
print(f"\n✅ تم حفظ ملف التدريب النهائي في:\n{SAVE_PATH}")

# ============================================================
# الحل الجذري: تطبيق تقنية InfoNCE (In-Batch Negatives)
# التدريب النهائي على البيانات النظيفة (Perfect Data)
# ============================================================

import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel, get_cosine_schedule_with_warmup
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import warnings, os

warnings.filterwarnings('ignore')

# 🎯 التعديلات الجديدة على المسارات
FILE_PATH  = '/content/drive/MyDrive/Perfect_Data.xlsx'
SAVE_PATH  = '/content/drive/MyDrive/legal_semantic_perfect_data' # مسار جديد لحماية الموديل القديم
MODEL_NAME = "aubmindlab/bert-base-arabertv2"
BATCH_SIZE = 16
EPOCHS     = 15
LR         = 2e-5
device     = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(f"🚀 يتم التشغيل الآن على بيئة: {device}")

# ============================================================
# 1. تحميل البيانات (مبسط وفعال)
# ============================================================
def load_data(path):
    try:
        df = pd.read_excel(path, sheet_name=0)
    except:
        df = pd.read_csv(path)

    df = df.dropna(subset=['text', 'enhanced_semantic_sentence'])
    df['input_text']  = df['text'].astype(str).str.strip()
    df['target_text'] = df['enhanced_semantic_sentence'].astype(str).str.strip()
    df['sector']      = df['القطاعات'].astype(str).str.strip()

    df['label_key'] = df['sector'] + " || " + df['target_text']
    unique_labels   = df['label_key'].unique()

    print(f"📊 إجمالي السجلات: {len(df)}")
    print(f"🏷️  عدد الجمل الهدف الفريدة: {len(unique_labels)}")

    train_df, temp_df = train_test_split(df, test_size=0.2, random_state=42)
    val_df, test_df   = train_test_split(temp_df, test_size=0.5, random_state=42)

    return train_df, val_df, test_df, unique_labels

# ============================================================
# 2. Dataset الجديد (بدون أمثلة سلبية يدوية - السلبية ستتولد تلقائياً)
# ============================================================
class LegalInfoNCEDataset(Dataset):
    def __init__(self, df, tokenizer, max_len=256):
        self.df = df.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self): return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        text_a = row['sector'] + " " + row['input_text']
        text_b = row['target_text']

        enc_a = self.tokenizer(text_a, max_length=self.max_len, padding='max_length', truncation=True, return_tensors='pt')
        enc_b = self.tokenizer(text_b, max_length=64, padding='max_length', truncation=True, return_tensors='pt')

        return {
            'input_ids_a':      enc_a['input_ids'].squeeze(),
            'attention_mask_a': enc_a['attention_mask'].squeeze(),
            'input_ids_b':      enc_b['input_ids'].squeeze(),
            'attention_mask_b': enc_b['attention_mask'].squeeze()
        }

# ============================================================
# 3. الموديل الرياضي الجديد (InfoNCE)
# ============================================================
class BiEncoderInfoNCE(torch.nn.Module):
    def __init__(self, model_name):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(model_name)
        # Scale factor (Temperature) لزيادة حدة الفروق بين الجمل
        self.scale = 20.0

    def mean_pool(self, token_embeddings, attention_mask):
        mask = attention_mask.unsqueeze(-1).float()
        return (token_embeddings * mask).sum(1) / torch.clamp(mask.sum(1), min=1e-9)

    def encode(self, input_ids, attention_mask):
        out = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        emb = self.mean_pool(out.last_hidden_state, attention_mask)
        # تطبيع رياضي (L2 Normalization) ضروري جداً هنا
        return torch.nn.functional.normalize(emb, p=2, dim=1)

    def forward(self, input_ids_a, attention_mask_a, input_ids_b, attention_mask_b):
        emb_a = self.encode(input_ids_a, attention_mask_a) # (batch, hidden)
        emb_b = self.encode(input_ids_b, attention_mask_b) # (batch, hidden)

        # ضرب المصفوفات لتوليد مصفوفة التشابه (كل جملة مع كل الجمل الأخرى)
        scores = torch.matmul(emb_a, emb_b.T) * self.scale
        return scores

# ============================================================
# 4. بناء الفهرس والاختبار (نفس العبقرية السابقة)
# ============================================================
def build_target_index(model, tokenizer, unique_labels, device):
    model.eval()
    target_embeddings, target_texts = [], []
    unique_targets = list(set([l.split(" || ")[1] for l in unique_labels]))

    print(f"\n🔨 بناء الفهرس الدلالي لـ {len(unique_targets)} جملة هدف...")
    for i in range(0, len(unique_targets), 32):
        batch = unique_targets[i:i+32]
        enc = tokenizer(batch, max_length=64, padding=True, truncation=True, return_tensors='pt').to(device)
        with torch.no_grad():
            emb = model.encode(enc['input_ids'], enc['attention_mask'])
        target_embeddings.append(emb.cpu().numpy())
        target_texts.extend(batch)

    return np.vstack(target_embeddings), target_texts

def predict_sentence(model, tokenizer, input_text, sector, target_embeddings, target_texts, device, top_k=3):
    model.eval()
    query = sector + " " + input_text
    enc = tokenizer(query, max_length=256, truncation=True, return_tensors='pt').to(device)
    with torch.no_grad():
        emb = model.encode(enc['input_ids'], enc['attention_mask']).cpu().numpy()

    sims = cosine_similarity(emb, target_embeddings)[0]
    top_idx = sims.argsort()[::-1][:top_k]
    return [(target_texts[i], sims[i]) for i in top_idx]

def evaluate_retrieval(model, tokenizer, test_df, target_embeddings, target_texts, device):
    correct_1, correct_3, total = 0, 0, len(test_df)

    print("\n🔍 بدء الاختبار النهائي الشامل...")
    for _, row in tqdm(test_df.iterrows(), total=total):
        preds = predict_sentence(model, tokenizer, row['input_text'], row['sector'], target_embeddings, target_texts, device, top_k=3)
        pred_texts = [p[0] for p in preds]
        ref = row['target_text'].strip()

        if pred_texts[0] == ref: correct_1 += 1
        if ref in pred_texts:    correct_3 += 1

    print(f"\n{'='*50}")
    print(f"🎯 التطابق التام (الخيار الأول) Exact Match @1:  {correct_1/total*100:.2f}%")
    print(f"🎯 التطابق التام (أول 3 خيارات) Exact Match @3:  {correct_3/total*100:.2f}%")
    print(f"{'='*50}")

# ============================================================
# 5. تشغيل النظام (Training Loop المحدث)
# ============================================================
def run_pipeline():
    train_df, val_df, test_df, unique_labels = load_data(FILE_PATH)
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = BiEncoderInfoNCE(MODEL_NAME).to(device)

    train_loader = DataLoader(LegalInfoNCEDataset(train_df, tokenizer), batch_size=BATCH_SIZE, shuffle=True, num_workers=2)

    optimizer = torch.optim.AdamW(model.parameters(), lr=LR)
    scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=150, num_training_steps=len(train_loader) * EPOCHS)
    loss_fn = torch.nn.CrossEntropyLoss()

    best_loss = float('inf')
    os.makedirs(SAVE_PATH, exist_ok=True)

    for epoch in range(EPOCHS):
        model.train()
        total_loss = 0
        loop = tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS}")
        for batch in loop:
            optimizer.zero_grad()

            scores = model(
                batch['input_ids_a'].to(device), batch['attention_mask_a'].to(device),
                batch['input_ids_b'].to(device), batch['attention_mask_b'].to(device)
            )

            labels = torch.arange(scores.size(0)).long().to(device)
            loss = loss_fn(scores, labels)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()

            total_loss += loss.item()
            loop.set_postfix(loss=f"{loss.item():.4f}")

        avg = total_loss / len(train_loader)
        print(f"📈 Epoch {epoch+1}: Loss={avg:.4f}")

        if avg < best_loss:
            best_loss = avg
            torch.save(model.state_dict(), f"{SAVE_PATH}/best_model.pt")
            print("🏆 تم حفظ الموديل (أداء أفضل)")

    # الاختبار النهائي
    model.load_state_dict(torch.load(f"{SAVE_PATH}/best_model.pt"))
    target_embs, target_texts = build_target_index(model, tokenizer, unique_labels, device)
    evaluate_retrieval(model, tokenizer, test_df, target_embs, target_texts, device)

run_pipeline()



# ============================================================
# 🧠 التدريب الشامل للموديل الموّلد (AraT5) مع مقاييس التقييم
# المقاييس المستخدمة: (Loss, ROUGE-1, ROUGE-2, ROUGE-L, Exact Match)
# ============================================================

import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, get_cosine_schedule_with_warmup
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import warnings, os

warnings.filterwarnings('ignore')

# 1. الإعدادات والمسارات
FILE_PATH  = '/content/drive/MyDrive/Perfect_Data.xlsx'
SAVE_PATH  = '/content/drive/MyDrive/legal_arat5_final'
MODEL_NAME = "UBC-NLP/AraT5-base"
BATCH_SIZE = 8
EPOCHS     = 10  # 10 دورات كافية جداً للتوليد
device     = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 2. دالة حساب مقياس ROUGE المخصصة للغة العربية
def arabic_rouge(refs, preds):
    r1_scores, r2_scores, rL_scores = [], [], []
    for ref, pred in zip(refs, preds):
        ref = ref.strip()
        pred = pred.strip()
        if not ref or not pred:
            r1_scores.append(0); r2_scores.append(0); rL_scores.append(0)
            continue
        ref_tokens, pred_tokens = ref.split(), pred.split()

        # ROUGE-1
        overlap_1 = len(set(ref_tokens) & set(pred_tokens))
        r1_scores.append(overlap_1 / max(len(ref_tokens), 1))

        # ROUGE-2
        ref_bigrams = set([(ref_tokens[i], ref_tokens[i+1]) for i in range(len(ref_tokens)-1)])
        pred_bigrams = set([(pred_tokens[i], pred_tokens[i+1]) for i in range(len(pred_tokens)-1)])
        overlap_2 = len(ref_bigrams & pred_bigrams)
        r2_scores.append(overlap_2 / max(len(ref_tokens)-1, 1))

        # ROUGE-L (أطول سلسلة متطابقة)
        def lcs(x, y):
            m, n = len(x), len(y)
            dp = [[0]*(n+1) for _ in range(m+1)]
            for i in range(1, m+1):
                for j in range(1, n+1):
                    if x[i-1] == y[j-1]: dp[i][j] = dp[i-1][j-1] + 1
                    else: dp[i][j] = max(dp[i-1][j], dp[i][j-1])
            return dp[m][n]

        rL_scores.append(lcs(ref_tokens, pred_tokens) / max(len(ref_tokens), 1))

    return np.mean(r1_scores), np.mean(r2_scores), np.mean(rL_scores)

# 3. تجهيز البيانات
print("⏳ جاري تحميل البيانات...")
df = pd.read_excel(FILE_PATH)
df = df.dropna(subset=['text', 'enhanced_semantic_sentence'])

# إعداد النص للتدريب الهجين (نضيف الجملة الدلالية كمرجع، وندمجها مع النص)
# ملاحظة: في التدريب نعلمه كيف يقلد المرجع ليولد الهدف
df['input_text']  = "المرجع: " + df['enhanced_semantic_sentence'].astype(str) + " [SEP] القطاع: " + df['القطاعات'].astype(str) + " | النص: " + df['text'].astype(str)
df['target_text'] = df['enhanced_semantic_sentence'].astype(str)

train_df, val_df = train_test_split(df, test_size=0.1, random_state=42)

class T5LegalDataset(Dataset):
    def __init__(self, data, tokenizer, max_in=256, max_out=64):
        self.data = data.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_in, self.max_out = max_in, max_out

    def __len__(self): return len(self.data)

    def __getitem__(self, idx):
        row = self.data.iloc[idx]
        inputs = self.tokenizer(row['input_text'], max_length=self.max_in, padding='max_length', truncation=True, return_tensors="pt")
        targets = self.tokenizer(row['target_text'], max_length=self.max_out, padding='max_length', truncation=True, return_tensors="pt")

        labels = targets['input_ids'].squeeze()
        labels[labels == self.tokenizer.pad_token_id] = -100
        return {
            'input_ids': inputs['input_ids'].squeeze(),
            'attention_mask': inputs['attention_mask'].squeeze(),
            'labels': labels
        }

# 4. إقلاع التدريب
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME).to(device)

train_loader = DataLoader(T5LegalDataset(train_df, tokenizer), batch_size=BATCH_SIZE, shuffle=True)
val_loader   = DataLoader(T5LegalDataset(val_df, tokenizer), batch_size=BATCH_SIZE, shuffle=False)

optimizer = torch.optim.AdamW(model.parameters(), lr=3e-5)
scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=200, num_training_steps=len(train_loader)*EPOCHS)

best_rougeL = 0.0
os.makedirs(SAVE_PATH, exist_ok=True)
print(f"🚀 بدء التدريب مع التقييم على بيئة {device}...")

for epoch in range(EPOCHS):
    # --- مرحلة التدريب (Training) ---
    model.train()
    total_loss = 0
    loop = tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS} [Train]")
    for batch in loop:
        optimizer.zero_grad()
        outputs = model(
            input_ids=batch['input_ids'].to(device),
            attention_mask=batch['attention_mask'].to(device),
            labels=batch['labels'].to(device)
        )
        loss = outputs.loss
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()
        total_loss += loss.item()
        loop.set_postfix(loss=f"{loss.item():.4f}")

    # --- مرحلة التقييم والتوليد (Validation & Generation) ---
    model.eval()
    all_preds, all_refs = [], []
    val_loop = tqdm(val_loader, desc=f"Epoch {epoch+1}/{EPOCHS} [Eval]")

    with torch.no_grad():
        for batch in val_loop:
            # التوليد الفعلي (نجعل الموديل يكتب بنفسه)
            generated_ids = model.generate(
                batch['input_ids'].to(device),
                attention_mask=batch['attention_mask'].to(device),
                max_new_tokens=64,
                num_beams=3,
                early_stopping=True
            )

            preds = [tokenizer.decode(g, skip_special_tokens=True) for g in generated_ids]

            # استرجاع النصوص الأصلية للمقارنة
            labels = batch['labels'].clone()
            labels[labels == -100] = tokenizer.pad_token_id
            refs = [tokenizer.decode(l, skip_special_tokens=True) for l in labels]

            all_preds.extend(preds)
            all_refs.extend(refs)

    # حساب المقاييس
    r1, r2, rL = arabic_rouge(all_refs, all_preds)
    exact_match = sum(1 for r, p in zip(all_refs, all_preds) if r.strip() == p.strip()) / len(all_refs)

    print(f"\n📊 نتائج التقييم للدورة {epoch+1}:")
    print(f"📉 Loss: {total_loss/len(train_loader):.4f}")
    print(f"📏 ROUGE-1: {r1*100:.2f}% | ROUGE-2: {r2*100:.2f}% | ROUGE-L: {rL*100:.2f}%")
    print(f"🎯 Exact Match: {exact_match*100:.2f}%")

    # عرض عينة توليد عشوائية لتريها بعينك
    idx = np.random.randint(0, len(all_preds))
    print(f"💡 المرجع : {all_refs[idx]}")
    print(f"🤖 التوليد : {all_preds[idx]}\n")

    # حفظ الموديل إذا تحسن ROUGE-L
    if rL > best_rougeL:
        best_rougeL = rL
        model.save_pretrained(SAVE_PATH)
        tokenizer.save_pretrained(SAVE_PATH)
        print("🏆 تم حفظ الموديل (توليد أفضل)!\n" + "="*50)

print(f"\n🎉 انتهى التدريب! أفضل ROUGE-L حصلنا عليه: {best_rougeL*100:.2f}%")







!pip install bert-score

import pandas as pd
import numpy as np
import torch
from transformers import AutoTokenizer, AutoModel
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, precision_score, recall_score
from tqdm import tqdm
import warnings

warnings.filterwarnings('ignore')

# ============================================================
# 1. الإعدادات والمسارات
# ============================================================
FILE_PATH  = '/content/drive/MyDrive/Perfect_Data.xlsx'
MODEL_PATH = '/content/drive/MyDrive/legal_semantic_perfect_data/best_model.pt'
MODEL_NAME = "aubmindlab/bert-base-arabertv2"
device     = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(f"🚀 يتم التشغيل للتقييم على بيئة: {device}")

# ============================================================
# 2. تعريف معمارية الموديل
# ============================================================
class BiEncoderInfoNCE(torch.nn.Module):
    def __init__(self, model_name):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(model_name)
        self.scale = 20.0

    def mean_pool(self, token_embeddings, attention_mask):
        mask = attention_mask.unsqueeze(-1).float()
        return (token_embeddings * mask).sum(1) / torch.clamp(mask.sum(1), min=1e-9)

    def encode(self, input_ids, attention_mask):
        out = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        emb = self.mean_pool(out.last_hidden_state, attention_mask)
        return torch.nn.functional.normalize(emb, p=2, dim=1)

# ============================================================
# 3. تحميل البيانات
# ============================================================
def get_test_data(path):
    df = pd.read_excel(path, sheet_name=0)
    df = df.dropna(subset=['text', 'enhanced_semantic_sentence'])
    df['input_text']  = df['text'].astype(str).str.strip()
    df['target_text'] = df['enhanced_semantic_sentence'].astype(str).str.strip()
    df['sector']      = df['القطاعات'].astype(str).str.strip()

    # دمج القطاع مع الهدف لإنشاء مفتاح فريد
    df['label_key'] = df['sector'] + " || " + df['target_text']
    unique_labels   = df['label_key'].unique()

    train_df, temp_df = train_test_split(df, test_size=0.2, random_state=42)
    val_df, test_df   = train_test_split(temp_df, test_size=0.5, random_state=42)

    return test_df, unique_labels

# ============================================================
# 4. دوال الاسترجاع المفلترة
# ============================================================
def build_sector_based_index(model, tokenizer, unique_labels, device):
    model.eval()
    sector_index = {}

    sector_to_targets = {}
    for label in unique_labels:
        sector, target = label.split(" || ")
        if sector not in sector_to_targets:
            sector_to_targets[sector] = []
        if target not in sector_to_targets[sector]:
            sector_to_targets[sector].append(target)

    print(f"\n🔨 بناء الفهارس الدلالية مفلترة حسب القطاعات (عدد القطاعات: {len(sector_to_targets)})...")

    for sector, targets in sector_to_targets.items():
        embeddings = []
        for i in range(0, len(targets), 32):
            batch = targets[i:i+32]
            enc = tokenizer(batch, max_length=64, padding=True, truncation=True, return_tensors='pt').to(device)
            with torch.no_grad():
                emb = model.encode(enc['input_ids'], enc['attention_mask'])
            embeddings.append(emb.cpu().numpy())

        sector_index[sector] = {
            'embeddings': np.vstack(embeddings),
            'texts': targets
        }

    return sector_index

def predict_sentence_filtered(model, tokenizer, input_text, sector, sector_index, device, top_k=3):
    model.eval()

    if sector not in sector_index:
        return [("قطاع غير معروف", 0.0)]

    target_embeddings = sector_index[sector]['embeddings']
    target_texts = sector_index[sector]['texts']

    query = sector + " " + input_text
    enc = tokenizer(query, max_length=256, truncation=True, return_tensors='pt').to(device)

    with torch.no_grad():
        emb = model.encode(enc['input_ids'], enc['attention_mask']).cpu().numpy()

    sims = cosine_similarity(emb, target_embeddings)[0]

    actual_top_k = min(top_k, len(target_texts))
    top_idx = sims.argsort()[::-1][:actual_top_k]

    return [(target_texts[i], sims[i]) for i in top_idx]

# ============================================================
# 5. التقييم الشامل بالمقاييس الجديدة (بما فيها BERTScore)
# ============================================================
def run_evaluation():
    test_df, unique_labels = get_test_data(FILE_PATH)

    print("\n⏳ جاري تحميل الموديل المدرب...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = BiEncoderInfoNCE(MODEL_NAME).to(device)

    model.load_state_dict(torch.load(MODEL_PATH, map_location=device), strict=False)
    model.eval()

    sector_index = build_sector_based_index(model, tokenizer, unique_labels, device)

    y_true = []
    y_pred = []
    correct_1, correct_3 = 0, 0
    total = len(test_df)

    print("\n🔍 بدء التقييم المفلتر (Filtered Retrieval)...")
    for _, row in tqdm(test_df.iterrows(), total=total):
        preds = predict_sentence_filtered(
            model, tokenizer, row['input_text'], row['sector'], sector_index, device, top_k=3
        )

        ref = row['target_text'].strip()
        top_pred = preds[0][0].strip()

        y_true.append(ref)
        y_pred.append(top_pred)

        if top_pred == ref: correct_1 += 1
        if ref in [p[0] for p in preds]: correct_3 += 1

    # الحسابات التقليدية
    f1 = f1_score(y_true, y_pred, average='weighted', zero_division=0)
    precision = precision_score(y_true, y_pred, average='weighted', zero_division=0)
    recall = recall_score(y_true, y_pred, average='weighted', zero_division=0)

    # حساب مقياس BERTScore
    print("\n⏳ جاري حساب BERTScore للذكاء الدلالي...")
    try:
        from bert_score import score as bert_score_func
        P, R, F1_bert = bert_score_func(y_pred, y_true, lang="ar", verbose=False)
        bert_f1_mean = F1_bert.mean().item() * 100
    except ImportError:
        print("⚠️ لم يتم العثور على مكتبة bert_score. يرجى تثبيتها باستخدام: !pip install bert-score")
        bert_f1_mean = 0.0

    print("\n" + "="*65)
    print(f"📊 نتائج أداء موديل الاسترجاع (بعد تطبيق الفلترة بالقطاع):")
    print("="*65)
    print(f"🎯 Exact Match @1 (Accuracy) : {correct_1/total*100:.2f}%")
    print(f"🎯 Exact Match @3            : {correct_3/total*100:.2f}%")
    print("-" * 65)
    print(f"✨ Precision (weighted)      : {precision:.4f}")
    print(f"✨ Recall (weighted)         : {recall:.4f}")
    print(f"🏆 F1-Score (weighted)       : {f1:.4f}")
    print("-" * 65)
    print(f"🧠 BERTScore F1 (فهم المعنى) : {bert_f1_mean:.2f}%")
    print("="*65)

# تشغيل
run_evaluation()



# ============================================================
# 🏛️ محرك الأتمتة الهجين النهائي (Master Hybrid RAG v4.0)
# استراتيجية: التوليد أولاً + تقييم AraBERT + الإنقاذ المفلتر
# ============================================================

import pandas as pd
import numpy as np
import torch
from transformers import AutoTokenizer, AutoModel, AutoModelForSeq2SeqLM
from sklearn.metrics.pairwise import cosine_similarity
import warnings

warnings.filterwarnings('ignore')

# ─────────────────────────────────────────
# 🎛️ منطقة التجارب (غيّر هذا الرقم لاختبار النظام)
# ─────────────────────────────────────────
# هذا هو الـ Threshold الذي يحدد متى نعتمد توليد AraT5، ومتى نرفضه للإنقاذ
SEMANTIC_MATCH_THRESHOLD = 0.60  # إذا كان التشابه الدلالي بين التوليد والنص الأصلي >= 60% نقبله

# ─────────────────────────────────────────
# 1. المسارات والإعدادات
# ─────────────────────────────────────────
FILE_PATH      = '/content/drive/MyDrive/Perfect_Data.xlsx'
RETRIEVER_PATH = '/content/drive/MyDrive/legal_semantic_perfect_data/best_model.pt'
GENERATOR_PATH = '/content/drive/MyDrive/legal_arat5_final'
BI_MODEL_NAME  = "aubmindlab/bert-base-arabertv2"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"🚀 يتم التشغيل الآن على بيئة: {device}")

# ─────────────────────────────────────────
# 2. تعريف معمارية AraBERT (لخطة الإنقاذ والتقييم)
# ─────────────────────────────────────────
class BiEncoderInfoNCE(torch.nn.Module):
    def __init__(self, model_name):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(model_name)

    def mean_pool(self, token_embeddings, attention_mask):
        mask = attention_mask.unsqueeze(-1).float()
        return (token_embeddings * mask).sum(1) / torch.clamp(mask.sum(1), min=1e-9)

    def encode(self, input_ids, attention_mask):
        out = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        emb = self.mean_pool(out.last_hidden_state, attention_mask)
        return torch.nn.functional.normalize(emb, p=2, dim=1)

# ─────────────────────────────────────────
# 3. إقلاع النماذج (تم حل مشكلة الـ strict)
# ─────────────────────────────────────────
print("⏳ جاري تحميل نماذج الذكاء الاصطناعي...")

# AraBERT (التقييم والإنقاذ)
bert_tokenizer = AutoTokenizer.from_pretrained(BI_MODEL_NAME)
bert_model     = BiEncoderInfoNCE(BI_MODEL_NAME).to(device)
# التعديل الصحيح للتحميل
checkpoint = torch.load(RETRIEVER_PATH, map_location=device, weights_only=False)
bert_model.load_state_dict(checkpoint, strict=False)
bert_model.eval()

# AraT5 (بطل التوليد)
t5_tokenizer = AutoTokenizer.from_pretrained(GENERATOR_PATH)
t5_model     = AutoModelForSeq2SeqLM.from_pretrained(GENERATOR_PATH).to(device)
t5_model.eval()

# ─────────────────────────────────────────
# 4. بناء الفهرس المفلتر للإنقاذ السريع
# ─────────────────────────────────────────
print("⏳ جاري بناء الفهارس الدلالية المفلترة حسب القطاع...")
df = pd.read_excel(FILE_PATH)
df = df.dropna(subset=['enhanced_semantic_sentence', 'القطاعات'])

sector_index = {}
for _, row in df.iterrows():
    sector = str(row['القطاعات']).strip()
    target = str(row['enhanced_semantic_sentence']).strip()

    if sector not in sector_index:
        sector_index[sector] = []
    if target not in sector_index[sector]:
        sector_index[sector].append(target)

for sector, targets in sector_index.items():
    embeddings = []
    for i in range(0, len(targets), 32):
        batch = targets[i:i+32]
        enc = bert_tokenizer(batch, max_length=64, padding=True, truncation=True, return_tensors='pt').to(device)
        with torch.no_grad():
            emb = bert_model.encode(enc['input_ids'], enc['attention_mask'])
        embeddings.append(emb.cpu().numpy())

    sector_index[sector] = {
        'embeddings': np.vstack(embeddings),
        'texts': targets
    }
print(f"✅ النظام جاهز! تم بناء فهارس لـ {len(sector_index)} قطاع.\n")

# ─────────────────────────────────────────
# 5. دوال الذكاء الاصطناعي الأساسية
# ─────────────────────────────────────────
def generate_only(sector, raw_text):
    """AraT5 يولد الجملة فقط بصيغة مبسطة تمنع التشتت"""
    prompt = f"{sector} [SEP] {raw_text}"
    enc = t5_tokenizer(prompt, return_tensors="pt", truncation=True, max_length=256).to(device)

    with torch.no_grad():
        outputs = t5_model.generate(
            enc['input_ids'],
            attention_mask=enc['attention_mask'],
            max_new_tokens=64,
            num_beams=5,
            no_repeat_ngram_size=3,
            length_penalty=1.2,
            early_stopping=True
        )
    return t5_tokenizer.decode(outputs[0], skip_special_tokens=True)

def retrieve_fallback(sector, raw_text):
    """AraBERT يتدخل لإنقاذ الموقف بمقارنة النص الخام مع الجمل الهدف"""
    if sector not in sector_index:
        return None, 0.0

    target_embeddings = sector_index[sector]['embeddings']
    target_texts = sector_index[sector]['texts']

    query = sector + " " + raw_text
    enc = bert_tokenizer(query, max_length=256, truncation=True, return_tensors='pt').to(device)

    with torch.no_grad():
        emb = bert_model.encode(enc['input_ids'], enc['attention_mask']).cpu().numpy()

    sims = cosine_similarity(emb, target_embeddings)[0]
    best_idx = sims.argsort()[::-1][0]

    return target_texts[best_idx], float(sims[best_idx])

# ─────────────────────────────────────────
# 6. المحرك الهجين النهائي (The Master Pipeline)
# ─────────────────────────────────────────
def hybrid_master_pipeline(sector, raw_text):
    print("\n" + "═" * 70)
    print(f"📁 القطاع   : {sector}")
    print(f"📄 النص     : {raw_text[:80]}...")
    print("─" * 70)

    # الخطوة 1: AraT5 يولد النص
    generated_tag = generate_only(sector, raw_text)

    # الخطوة 2: AraBERT يقيّم جودة التوليد بالتشابه الدلالي الحقيقي
    enc_input = bert_tokenizer(sector + " " + raw_text, max_length=256, truncation=True, return_tensors='pt').to(device)
    enc_gen   = bert_tokenizer(sector + " " + generated_tag, max_length=64, truncation=True, return_tensors='pt').to(device)

    with torch.no_grad():
        emb_input = bert_model.encode(enc_input['input_ids'], enc_input['attention_mask']).cpu().numpy()
        emb_gen   = bert_model.encode(enc_gen['input_ids'], enc_gen['attention_mask']).cpu().numpy()

    true_semantic_score = float(cosine_similarity(emb_input, emb_gen)[0][0])

    # الخطوة 3: اتخاذ القرار (الراوتر الذكي)
    if true_semantic_score >= SEMANTIC_MATCH_THRESHOLD:
        print(f"🤖 المسار   : ✅ تم الاعتماد على توليد AraT5")
        print(f"📈 ارتباط التوليد: {true_semantic_score:.1%} (أعلى من العتبة المطلوبة {SEMANTIC_MATCH_THRESHOLD:.1%})")
        print("─" * 70)
        print(f"🎯 النتيجة  : {generated_tag}")
        print(f"🔒 مصدر الحل: 🧠 التوليد المباشر (Generation)")

    else:
        print(f"🤖 المسار   : ⚠️ توليد AraT5 كان عشوائياً (ارتباط: {true_semantic_score:.1%}) -> تفعيل الإنقاذ!")

        # الخطوة 4: تفعيل خطة الإنقاذ المفلترة (Fallback)
        fallback_ref, fallback_score = retrieve_fallback(sector, raw_text)

        if fallback_ref:
            print(f"🔍 دقة البحث : {fallback_score:.1%} (مدى تطابق النص المدخل مع الهدف بالقاموس)")
            print("─" * 70)
            print(f"🎯 النتيجة  : {fallback_ref}")
            print(f"🔒 مصدر الحل: 🛡️ الاسترجاع القانوني المفلتر (Retrieval Fallback)")
        else:
            print("─" * 70)
            print(f"🎯 النتيجة  : {generated_tag}")
            print(f"🔒 مصدر الحل: ⚠️ التوليد (لا يوجد مرجع إنقاذ لهذا القطاع)")

    print("═" * 70)

# ─────────────────────────────────────────
# 7. واجهة الاختبار التفاعلية
# ─────────────────────────────────────────
print("\n🏛️  نظام التنظيم الهجين جاهز للاختبار الدقيق!")
print(f"🎯 العتبة الحالية لقبول التوليد (Threshold): {SEMANTIC_MATCH_THRESHOLD:.1%}")

while True:
    sector = input("\n📁 أدخل القطاع (أو 'خروج'): ").strip()
    if sector in ['خروج', 'exit', 'quit']: break
    raw_text = input("📄 أدخل النص القانوني الخام:\n> ").strip()
    if not raw_text: continue

    hybrid_master_pipeline(sector, raw_text)

"""ملاحظه : تم تجربة العتبه 70  و50  و65 ، 70 كان متشدد جدا على مودل الجنريشن و65 كذالك اما 50 كان يعتمد مودل الجنريشن بثقه عاليه رغم انوا الناتج خاطئ"""